// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef form_h
#define form_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>
Fl_Double_Window* make_window();
#endif
