// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "form.h"

Fl_Double_Window* make_window() {
	Fl_Double_Window* w;
	{ Fl_Double_Window* o = new Fl_Double_Window(917, 1169, "Photovoltaic Creativity");
	w = o; if (w) {/* empty */ }
	o->labeltype(FL_NORMAL_LABEL);
	{ Fl_Group* o = new Fl_Group(670, 40, 200, 600, "Input Values");
	o->box(FL_THIN_UP_BOX);
	{ Fl_Value_Input* o = new Fl_Value_Input(760, 60, 95, 23, "Latitude");
	o->maximum(360);
	o->value(35);
	} // Fl_Value_Input* o
	{ Fl_Value_Input* o = new Fl_Value_Input(760, 90, 95, 23, "Beta (Tilt)");
	o->maximum(90);
	o->value(30);
	} // Fl_Value_Input* o
	{ Fl_Value_Input* o = new Fl_Value_Input(760, 120, 95, 23, "delta");
	o->maximum(90);
	o->value(23.09);
	} // Fl_Value_Input* o
	{ Fl_Value_Input* o = new Fl_Value_Input(760, 150, 95, 23, "G_B");
	o->maximum(90);
	o->value(23.09);
	} // Fl_Value_Input* o
	{ new Fl_Button(685, 590, 170, 35, "Compute");
	} // Fl_Button* o
	o->end();
	} // Fl_Group* o
	{ Fl_Box* o = new Fl_Box(25, 25, 600, 600, "Pannello");
	o->box(FL_EMBOSSED_BOX);
	} // Fl_Box* o
	{ new Fl_Text_Display(25, 645, 600, 400, "Results");
	} // Fl_Text_Display* o
	o->end();
	} // Fl_Double_Window* o
	return w;
}
