// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "form.h"
#include "Frame.h"

Frame* scene;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { 
	  Fl_Double_Window* o = new Fl_Double_Window(917, 1169, "Photovoltaic Creativity");
    w = o; 
	if (w) {
		/* empty */
	}
    { Fl_Group* o = new Fl_Group(670, 40, 200, 600, "Input Values");
      { new Fl_Value_Input(760, 65, 15, 24, "Latitudine");
      } // Fl_Value_Input* o
      { new Fl_Value_Input(760, 91, 15, 24, "Longitudine");
      } // Fl_Value_Input* o
      o->end();
    } // Fl_Group* o
    { 	
		new Fl_Box(20, 20, 606, 606, "Pannello");

    } // Fl_Box* o
    o->end();
	o->show();
	scene = new Frame(23, 23, 600, 600, 0); //TODO
	scene->show();
  } // Fl_Double_Window* o
  return w;
}
