// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef PVCreativityUI_h
#define PVCreativityUI_h
#include <Windows.h>
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
#include "PanelView.h"
#include <FL/Fl_Text_Display.H>

class PVCreativityUI {
public:
  PVCreativityUI();
protected:
public:
  Fl_Value_Input *L;
  Fl_Value_Input *beta;
  Fl_Value_Input *delta;
  Fl_Value_Input *G_B;
protected:
  Fl_Button *compute;
public:
  PanelView *panel;
  Fl_Text_Display *results;
};
#endif
